---

# MySQL passwords
database_root_password: cloudPass
database_cloud_password: cloudPass

# NFS server
nfs_secondary_storage_host: 127.0.0.1

# CloudStack Ubuntu repo
cloudstack_repo_url: http://cloudstack.apt-get.eu/ubuntu/ trusty 4.4
cloudstack_repo_key: http://cloudstack.apt-get.eu/release.asc
cloudstack_repo_key_id: 86C278E3

# System VM url
url_systemvm_template: http://cloudstack.apt-get.eu/systemvm/4.4/systemvm64template-4.4.1-7-kvm.qcow2.bz2

# NFS domain for the NFS service on the host
nfs_domain: domain.net

# Bridge for CloudStack setup
host_interface_device: eth0
host_interface_bridge: cloudbr0

# Main (public) DNS server and domain name for the host
host_dns1: 8.8.4.4
host_dns_domain: domain.net

# Allow root to make directly ssh connection on CS node (need for CloudStack setup)
# and define a password to root
# if it's already done, change to false
host_enable_ssh_direct_root: true
host_root_password: cloudPass

# Option to add or not the APT KEY
add_apt_key: true

